name: Build on devel merge

on:
  push:
    branches:
      - devel

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          
       - name: Maven build uber JAR
         run: mvn -B clean package -Dquarkus.package.type=uber-jar -DskipTests

      - name: Upload Uber JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: uber-jar
          path: target/*-runner.jar

